name: Scheduled Task

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  run-task:
    runs-on: ubuntu-latest  # Still needed as the host runner
    container: ghcr.io/kourpa/usc-runner:lases
    concurrency: 
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 1
          
      - name: Run Script
        run: /run.sh
